sudo: false
language: node_js
cache:
  direcories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test-all
after_success:
  - npm run build
  - npm run report-coverage
